services:
  log-app:
    build: .
    container_name: python-logger
    volumes:
      - ~/.aws:/root/.aws:ro
    environment:
      AWS_REGION: us-east-1
      CW_LOG_GROUP: python-logger
      CW_LOG_STREAM: shahid-stream
      LOGSTASH_HOST: 172.31.3.134
      LOGSTASH_PORT: 5044