services:
  log-app:
    build: .
    container_name: python-logger
    volumes:
      - ~/.aws:/root/.aws:ro
    environment:
      AWS_REGION: ap-south-1
      CW_LOG_GROUP: python-logger
      CW_LOG_STREAM: shahid-stream
      LOGSTASH_HOST: elk.tekbay.click
      LOGSTASH_PORT: 5044